version: 0.2
phases:
  pre_build:
    commands:
      - curl -fsSL https://raw.githubusercontent.com/thii/aws-codebuild-extras/master/install >> extras.sh
      - . ./extras.sh
  build:
    commands:
      - echo $CODEBUILD_GIT_MESSAGE
